[desktop]
secret_key=mysecretkey123
http_host=0.0.0.0
http_port=8888
# Tắt giới hạn upload size (-1 = unlimited)
max_upload_size=-1

[filebrowser]
# Tăng chunk size lên 256MB (phù hợp với block size HDFS của bạn)
upload_chunk_size=268435456

[hadoop]
[[hdfs_clusters]]
[[[default]]]
fs_defaultfs=hdfs://namenode:9000
webhdfs_url=http://namenode:9870/webhdfs/v1
hadoop_conf_dir=/etc/hadoop/conf