version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    volumes:
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop_cluster
    networks:
      hadoop_net:
    deploy:
      placement:
        constraints:
          - node.labels.type == leader
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - ./config/core-site.xml:/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./datanode:/hadoop/dfs/data
    networks:
      - hadoop_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == slave

    ports:
      - "9864:9864"

networks:
  hadoop_net:
    driver: overlay
    attachable: true